### ISSUE TITLE
Excel Records - Notification

### ISSUE THREAD

**Issue by MasterAdmin2** [pxlrbt/filament-excel#161] opened 2023-12-23 07:19 UTC
Hello sir i am using laravel with filament's latest version and I installed your module with Composer,

now, I configured it like this on my resource page

```php
ExportAction::make()->exports([
                ExcelExport::make('form')
                    ->except([
                        'created_at',
                        'updated_at',
                        'deleted_at',
                    ])
                    ->fromModel()
                    ->queue()
                    ->withChunkSize(500)
                    ->askForWriterType(),
            ])
``` 

now what I want is, to send a notification when the file is ready to download, but it is not saving notifications, as laravel filament provides.

so my question is, is that possible to handle it that way, so that if I come after an hour or day then i can also download the file till I haven't cleared notifications. 

adding a snapshot for a better understanding

https://github.com/pxlrbt/filament-excel/assets/28727446/1b2d5967-6ec6-4651-9396-1351020d5a6e

**Comment by MasterAdmin2** [comment] 2023-12-23 08:31
i solved this by adding 2 lines in 2 files, it may help

vendor/pxlrbt/filament-excel/src/Exports/ExcelExport.php
inside this file I added 

`Notification::make()
            ->title(__('filament-excel::notifications.queued.title'))
            ->body(__('filament-excel::notifications.queued.body'))
            ->success()
            ->sendToDatabase(auth()->user()) // this line
            ->seconds(5)
            ->icon('heroicon-o-arrow-down-tray')
            ->send();`


and inside this file
vendor/pxlrbt/filament-excel/src/FilamentExcelServiceProvider.php
I added 

`Notification::make(data_get($export, 'id'))
                ->title(__('filament-excel::notifications.download_ready.title'))
                ->body(__('filament-excel::notifications.download_ready.body'))
                ->success()
                ->icon('heroicon-o-arrow-down-tray')
                ->actions([
                    Action::make('download')
                        ->label(__('filament-excel::notifications.download_ready.download'))
                        ->url($url, shouldOpenInNewTab: true)
                        ->button()
                        ->close(),
                ])
                ->sendToDatabase(auth()->user()) // this line
                ->persistent()
                ->send();`

I possible can you implement in master so that it will be verified by you and whenever we run update update it will be present, and I am pretty much sure, everyone will like this.

**Comment by pxlrbt** [comment] 2023-12-27 07:14
Closing as duplicate of #108

**Closed by pxlrbt** 2023-12-27 07:14 UTC
