### ISSUE TITLE
Filament Database Notification Deleted File

### ISSUE THREAD

**Issue by Umar-Farooq-Shafi** [pxlrbt/filament-excel#174] opened 2024-01-17 11:28 UTC
The notification shows the export even if the file is deleted after the first click.

> Remove the notification or not delete the file if the user has already downloaded the file!

**Comment by MasterAdmin2** [comment] 2024-01-22 13:25
> The notification shows the export even if the file is deleted after the first click.
> 
> > Remove the notification or not delete the file if the user has already downloaded the file!

yes, it saves the server space, if you repeatedly save all files of all exports it will consume space,

**Comment by pxlrbt** [comment] 2024-01-22 13:38
@MasterAdmin2 That's not what the issue is about. It's about the Notification still showing even when the file was removed already.

**Comment by Umar-Farooq-Shafi** [comment] 2024-01-22 14:45
Yes

**Comment by MasterAdmin2** [comment] 2024-01-24 09:37
> @MasterAdmin2 That's not what the issue is about. It's about the Notification still showing even when the file was removed.

corrected function is

```php
if ( Filament ::getCurrentPanel () -> hasDatabaseNotifications () ) {
					Notification ::make ( data_get ( $export , 'id' ) )
						-> title ( __ ( 'filament-excel::notifications.download_ready.title' ) )
						-> body ( __ ( 'filament-excel::notifications.download_ready.body' ) )
						-> success ()
						-> icon ( 'heroicon-o-arrow-down-tray' )
						-> actions ( [
							Action ::make ( 'download' )
								-> label ( __ ( 'filament-excel::notifications.download_ready.download' ) )
								-> url ( $url , shouldOpenInNewTab : true )
								-> button ()
								-> close ()
						] )
						-> persistent ()
						-> sendToDatabase ( auth () -> user () );
``` 


You missed adding the close-after button in the file. that's why that notification was there even after the download

**Comment by salvationarinze** [comment] 2024-03-06 22:51
Please is there a quick fix for this or do we wait for a merge?

**Comment by muzhawir** [comment] 2024-07-10 21:34
> Please is there a quick fix for this or do we wait for a merge?

I hope this fix is merged :pray: , because those who use database notifications will definitely get this error message when pressing the download button a second time:

![image](https://github.com/pxlrbt/filament-excel/assets/7391703/df17cf65-2b98-49b7-ac67-a5b9116f87ab)

**Closed** 2024-07-11 07:52 UTC

**Comment by muzhawir** [comment] 2024-07-11 20:24
Thank you very much!
